<?php 
$this->title = "delete an alb";
$this->headTitle($this->title);
?>
<p>r u sure to delete '<?php echo $this->escape($this->album['title'])."by".$this->escape($this->album['artist'])."?"; ?></p>
<form action="<?php echo $this->url(array('actoin'=>'delete')); ?>" method='post'>
<div>
	<input type="hidden" name="id" value="<?php echo $this->album['id'] ?>" />
	<input type="submit" name="del" value="Yes" />
	<input type="submit" name="del" value="No" />
</div>

</form>
