<?php 
$this->title = "my albums";
$this->headTitle($this->title);
$this->headTitle("test headTitle");
?>
<img src='/download/' />
<p><a href="<?php echo $this->url(array(
	'controller'=>'index',
	'action'=>'add'
)); ?>">Add new</a></p>
<table>
<tr>
	<th>Title</th>
	<th>artist</th>
	<th>&nbsp;</th>
</tr>
<?php foreach($this->albums as $album): ?>
<tr>
	<td><?php echo $this->escape($album->title); ?></td>
	<td><?php echo $this->escape($album->artist); ?></td>
	<td>
		<a href="<?php echo $this->url(array(
			'controller'=>'index',
			'action'=>'edit',
			'id'=>$album->id
		)); ?>" >Edit</a>
		<a href="<?php echo $this->url(array(
			'controller'=>'index',
			'action'=>'delete',
			'id'=>$album->id
		)); ?>" >del</a>
	</td>
</tr>
<?php endforeach; ?>
</table>
